@startuml
interface FileProcessor {
    +validateFileType()
    +findActualHeader()
    +skipMetadataRows()
    +processDataRows()
    +transformData()
}

abstract class AbstractFileHandler {
    #detectHeaderRow()
    #cleanEmptyRows()
    #validateDataFormat()
    #parseMetadata()
}

class CSVHandler extends AbstractFileHandler {
    -csvParser
    +readCSV()
}

class ExcelHandler extends AbstractFileHandler {
    -excelReader
    +readExcel()
}

class DataTransformer {
    +normalize()
    +addSequentialId()
    +cleanData()
}

CSVHandler --> DataTransformer
ExcelHandler --> DataTransformer
@enduml